# Generated by Django 6.0.4 on 2026-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
